[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Pour ESP32-S3 : décommenter la ligne suivante
; board = esp32-s3-devkitc-1

; Pour ESP32-C3 : décommenter la ligne suivante
; board = esp32-c3-devkitm-1
